### ISSUE TITLE
DB missing?

### ISSUE THREAD

**Issue by ghost** [AzureADQuickStarts/AppModelv2-WebApp-WebAPI-OpenIDConnect-DotNet#4]
Where do I get the DB file ??

the TodoList_ServiceContext-20150616144500 database seems to be missing?

the connection string points to TodoList_ServiceContext-20150616144500.mdf but there is no such file in the app data folders?

**Comment by jmprieur** [comment]
I should be created on the fly. which version of VS do yo use?
